#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
pinyin2zhuyin_dict = {
    "b": "ㄅ", "p": "ㄆ", "m": "ㄇ", "f": "ㄈ",
    "d": "ㄉ", "t": "ㄊ", "n": "ㄋ", "l": "ㄌ",
    "g": "ㄍ", "k": "ㄎ", "h": "ㄏ",
    "j": "ㄐ", "q": "ㄑ", "x": "ㄒ",
    "zh": "ㄓ", "ch": "ㄔ", "sh": "ㄕ", "r": "ㄖ",
    "z": "ㄗ", "c": "ㄘ", "s": "ㄙ",
    "y": "一", "w": "ㄨ",
    # Rhymes
    "a": "ㄚ", "o": "ㄛ", "e": "ㄜ",
    "i": "一", "u": "ㄨ", "v": "ㄩ",
    "ai": "ㄞ", "ei": "ㄟ", "ui": "ㄨㄟ",
    "ao": "ㄠ", "ou": "ㄡ", "iu": "一ㄡ",
    "an": "ㄢ", "en": "ㄣ", "in": "一ㄣ",
    "ang": "ㄤ", "eng": "ㄥ", "ing": "一ㄥ",
    "ong": "ㄨㄥ", "ie": "一ㄝ", "er": "ㄦ",
    "ue": "ㄩㄝ", "ve": "ㄩㄝ", # 'ue' is same as 've', for typo
    "un": "ㄨㄣ", "vn": "ㄩㄣ", "ia": "一ㄚ",
    "ua": "ㄨㄚ", "uan": "ㄨㄢ", "van": "ㄩㄢ",
    "uai": "ㄨㄞ", "uo": "ㄨㄛ", "iong": "ㄩㄥ",
    "iang": "一ㄤ", "uang": "ㄨㄤ", "ian": "一ㄢ",
    "iao": "一ㄠ"
}

zhuyin2pinyin_dict = {
    "ㄅ": "b", "ㄆ": "p", "ㄇ": "m", "ㄈ": "f",
    "ㄉ": "d", "ㄊ": "t", "ㄋ": "n", "ㄌ": "l",
    "ㄍ": "g", "ㄎ": "k", "ㄏ": "h",
    "ㄐ": "j", "ㄑ": "q", "ㄒ": "x",
    "ㄓ": "zh", "ㄔ": "ch", "ㄕ": "sh", "ㄖ": "r",
    "ㄗ": "z", "ㄘ": "c", "ㄙ": "s",

    # Rhymes
    "ㄚ": "a", "ㄛ": "o", "ㄜ": "e", "ㄝ": "e",
    "一": "i", "ㄨ": "u", "ㄩ": "v",
    "ㄞ": "ai", "ㄟ": "ei", "ㄦ": "er",
    "ㄠ": "ao", "ㄡ": "ou",
    "ㄢ": "an", "ㄣ": "en",
    "ㄤ": "ang", "ㄥ": "eng",

    "ㄨㄥ": "ong", "一ㄝ": "ie",
    "一ㄡ": "iu", "一ㄣ": "in", "一ㄥ": "ing",
    "ㄩㄝ": "ve",
    "ㄨㄣ": "un", "ㄩㄣ": "vn", "一ㄚ": "ia",
    "ㄨㄚ": "ua", "ㄨㄢ": "uan", "ㄩㄢ": "van",
    "ㄨㄞ": "uai", "ㄨㄛ": "uo", "ㄩㄥ": "iong",
    "一ㄤ": "iang", "ㄨㄤ": "uang", "一ㄢ": "ian",
    "一ㄠ": "iao", "ㄨㄟ": "ui"
}

pinyin_tone_dict = {
    'a': ['a', 'ā', 'á', 'ǎ', 'à'],
    'o': ['o', 'ō', 'ó', 'ǒ', 'ò'],
    'e': ['e', 'ē', 'é', 'ě', 'è'],
    'i': ['i', 'ī', 'í', 'ǐ', 'ì'],
    'u': ['u', 'ū', 'ú', 'ǔ', 'ù'],
    'ü': ['ü', 'ǖ', 'ǘ', 'ǚ', 'ǜ']
}

zhuyin_tones = ["˙", "ˉ", "ˊ", "ˇ", "ˋ"]
zhuyin_tones2num = {zhu : idx for idx, zhu in enumerate(zhuyin_tones)}
rhymes = set(['a','e','i','o','u','v'])

def isRhymes(c):
    return c in rhymes

def isConsonant(c):
    return c >= 'a' and c <= 'z' and not c in rhymes

zhuyin_hanpin_stdpin = [("ㄅㄚ","ba","ba"),
("ㄅㄛ","bo","bo"),
("ㄅㄞ","bai","bai"),
("ㄅㄟ","bei","bei"),
("ㄅㄠ","bao","bao"),
("ㄅㄢ","ban","ban"),
("ㄅㄣ","ben","ben"),
("ㄅㄤ","bang","bang"),
("ㄅㄥ","beng","beng"),
("ㄅㄧ","bi","bi"),
("ㄅㄧㄝ","bie","bie"),
("ㄅㄧㄠ","biao","biao"),
("ㄅㄧㄢ","bian","bian"),
("ㄅㄧㄣ","bin","bin"),
("ㄅㄧㄥ","bing","bing"),
("ㄅㄨ","bu","bu"),
("ㄆㄚ","pa","pa"),
("ㄆㄛ","po","po"),
("ㄆㄞ","pai","pai"),
("ㄆㄟ","pei","pei"),
("ㄆㄠ","pao","pao"),
("ㄆㄡ","pou","pou"),
("ㄆㄢ","pan","pan"),
("ㄆㄣ","pen","pen"),
("ㄆㄤ","pang","pang"),
("ㄆㄥ","peng","peng"),
("ㄆㄧ","pi","pi"),
("ㄆㄧㄝ","pie","pie"),
("ㄆㄧㄠ","piao","piao"),
("ㄆㄧㄢ","pian","pian"),
("ㄆㄧㄣ","pin","pin"),
("ㄆㄧㄥ","ping","ping"),
("ㄆㄨ","pu","pu"),
("ㄇㄚ","ma","ma"),
("ㄇㄛ","mo","mo"),
("ㄇㄞ","mai","mai"),
("ㄇㄟ","mei","mei"),
("ㄇㄠ","mao","mao"),
("ㄇㄡ","mou","mou"),
("ㄇㄢ","man","man"),
("ㄇㄣ","men","men"),
("ㄇㄤ","mang","mang"),
("ㄇㄥ","meng","meng"),
("ㄇㄧ","mi","mi"),
("ㄇㄧㄝ","mie","mie"),
("ㄇㄧㄠ","miao","miao"),
("ㄇㄧㄡ","miu","miou"),
("ㄇㄧㄢ","mian","mian"),
("ㄇㄧㄣ","min","min"),
("ㄇㄧㄥ","ming","ming"),
("ㄇㄨ","mu","mu"),
("ㄈㄚ","fa","fa"),
("ㄈㄛ","fo","fo"),
("ㄈㄟ","fei","fei"),
("ㄈㄡ","fou","fou"),
("ㄈㄢ","fan","fan"),
("ㄈㄣ","fen","fen"),
("ㄈㄤ","fang","fang"),
("ㄈㄥ","feng","fong"),
("ㄈㄨ","fu","fu"),
("ㄉㄚ","da","da"),
("ㄉㄜ","de","de"),
("ㄉㄞ","dai","dai"),
("ㄉㄟ","dei","dei"),
("ㄉㄠ","dao","dao"),
("ㄉㄡ","dou","dou"),
("ㄉㄢ","dan","dan"),
("ㄉㄤ","dang","dang"),
("ㄉㄥ","deng","deng"),
("ㄉㄧ","di","di"),
("ㄉㄧㄝ","die","die"),
("ㄉㄧㄠ","diao","diao"),
("ㄉㄧㄡ","diu","diou"),
("ㄉㄧㄢ","dian","dian"),
("ㄉㄧㄥ","ding","ding"),
("ㄉㄨ","du","du"),
("ㄉㄨㄛ","duo","duo"),
("ㄉㄨㄟ","dui","duei"),
("ㄉㄨㄢ","duan","duan"),
("ㄉㄨㄣ","dun","dun"),
("ㄉㄨㄥ","dong","dong"),
("ㄊㄚ","ta","ta"),
("ㄊㄜ","te","te"),
("ㄊㄞ","tai","tai"),
("ㄊㄠ","tao","tao"),
("ㄊㄡ","tou","tou"),
("ㄊㄢ","tan","tan"),
("ㄊㄤ","tang","tang"),
("ㄊㄥ","teng","teng"),
("ㄊㄧ","ti","ti"),
("ㄊㄧㄝ","tie","tie"),
("ㄊㄧㄠ","tiao","tiao"),
("ㄊㄧㄢ","tian","tian"),
("ㄊㄧㄥ","ting","ting"),
("ㄊㄨ","tu","tu"),
("ㄊㄨㄛ","tuo","tuo"),
("ㄊㄨㄟ","tui","tuei"),
("ㄊㄨㄢ","tuan","tuan"),
("ㄊㄨㄣ","tun","tun"),
("ㄊㄨㄥ","tong","tong"),
("ㄋㄚ","na","na"),
("ㄋㄞ","nai","nai"),
("ㄋㄟ","nei","nei"),
("ㄋㄠ","nao","nao"),
("ㄋㄡ","nou","nou"),
("ㄋㄢ","nan","nan"),
("ㄋㄤ","nang","nang"),
("ㄋㄥ","neng","neng"),
("ㄋㄧ","ni","ni"),
("ㄋㄧㄝ","nie","nie"),
("ㄋㄧㄠ","niao","niao"),
("ㄋㄧㄡ","niu","niou"),
("ㄋㄧㄢ","nian","nian"),
("ㄋㄧㄣ","nin","nin"),
("ㄋㄧㄤ","niang","niang"),
("ㄋㄧㄥ","ning","ning"),
("ㄋㄨ","nu","nu"),
("ㄋㄨㄛ","nuo","nuo"),
("ㄋㄨㄢ","nuan","nuan"),
("ㄋㄨㄣ","nun","nun"),
("ㄋㄨㄥ","nong","nong"),
("ㄋㄩ","nyu","nyu"),
("ㄋㄩㄝ","nyue","nyue"),
("ㄌㄚ","la","la"),
("ㄌㄜ","le","le"),
("ㄌㄞ","lai","lai"),
("ㄌㄟ","lei","lei"),
("ㄌㄠ","lao","lao"),
("ㄌㄡ","lou","lou"),
("ㄌㄢ","lan","lan"),
("ㄌㄤ","lang","lang"),
("ㄌㄥ","leng","leng"),
("ㄌㄧ","li","li"),
("ㄌㄧㄚ","lia","lia"),
("ㄌㄧㄝ","lie","lie"),
("ㄌㄧㄠ","liao","liao"),
("ㄌㄧㄡ","liu","liou"),
("ㄌㄧㄢ","lian","lian"),
("ㄌㄧㄣ","lin","lin"),
("ㄌㄧㄤ","liang","liang"),
("ㄌㄧㄥ","ling","ling"),
("ㄌㄨ","lu","lu"),
("ㄌㄨㄛ","luo","luo"),
("ㄌㄨㄢ","luan","luan"),
("ㄌㄨㄣ","lun","lun"),
("ㄌㄨㄥ","long","long"),
("ㄌㄩ","lü","lyu"),
("ㄌㄩㄝ","lyue","lyue"),
("ㄌㄩㄢ","lyuan","lyuan"),
("ㄌㄩㄣ","lyun","lyun"),
("ㄍㄚ","ga","ga"),
("ㄍㄜ","ge","ge"),
("ㄍㄞ","gai","gai"),
("ㄍㄟ","gei","gei"),
("ㄍㄠ","gao","gao"),
("ㄍㄡ","gou","gou"),
("ㄍㄢ","gan","gan"),
("ㄍㄣ","gen","gen"),
("ㄍㄤ","gang","gang"),
("ㄍㄥ","geng","geng"),
("ㄍㄨ","gu","gu"),
("ㄍㄨㄚ","gua","gua"),
("ㄍㄨㄛ","guo","guo"),
("ㄍㄨㄞ","guai","guai"),
("ㄍㄨㄟ","gui","guei"),
("ㄍㄨㄢ","guan","guan"),
("ㄍㄨㄣ","gun","gun"),
("ㄍㄨㄤ","guang","guang"),
("ㄍㄨㄥ","gong","gong"),
("ㄎㄚ","ka","ka"),
("ㄎㄜ","ke","ke"),
("ㄎㄞ","kai","kai"),
("ㄎㄠ","kao","kao"),
("ㄎㄡ","kou","kou"),
("ㄎㄢ","kan","kan"),
("ㄎㄣ","ken","ken"),
("ㄎㄤ","kang","kang"),
("ㄎㄥ","keng","keng"),
("ㄎㄨ","ku","ku"),
("ㄎㄨㄚ","kua","kua"),
("ㄎㄨㄛ","kuo","kuo"),
("ㄎㄨㄞ","kuai","kuai"),
("ㄎㄨㄟ","kui","kuei"),
("ㄎㄨㄢ","kuan","kuan"),
("ㄎㄨㄣ","kun","kun"),
("ㄎㄨㄤ","kuang","kuang"),
("ㄎㄨㄥ","kong","kong"),
("ㄏㄚ","ha","ha"),
("ㄏㄜ","he","he"),
("ㄏㄞ","hai","hai"),
("ㄏㄟ","hei","hei"),
("ㄏㄠ","hao","hao"),
("ㄏㄡ","hou","hou"),
("ㄏㄢ","han","han"),
("ㄏㄣ","hen","hen"),
("ㄏㄤ","hang","hang"),
("ㄏㄥ","heng","heng"),
("ㄏㄨ","hu","hu"),
("ㄏㄨㄚ","hua","hua"),
("ㄏㄨㄛ","huo","huo"),
("ㄏㄨㄞ","huai","huai"),
("ㄏㄨㄟ","hui","huei"),
("ㄏㄨㄢ","huan","huan"),
("ㄏㄨㄣ","hun","hun"),
("ㄏㄨㄤ","huang","huang"),
("ㄏㄨㄥ","hong","hong"),
("ㄐㄧ","ji","ji"),
("ㄐㄧㄚ","jia","jia"),
("ㄐㄧㄝ","jie","jie"),
("ㄐㄧㄠ","jiao","jiao"),
("ㄐㄧㄡ","jiu","jiou"),
("ㄐㄧㄢ","jian","jian"),
("ㄐㄧㄣ","jin","jin"),
("ㄐㄧㄤ","jiang","jiang"),
("ㄐㄧㄥ","jing","jing"),
("ㄐㄩ","ju","jyu"),
("ㄐㄩㄝ","jue","jyue"),
("ㄐㄩㄢ","juan","jyuan"),
("ㄐㄩㄣ","jun","jyun"),
("ㄐㄩㄥ","jiong","jyong"),
("ㄑㄧ","qi","ci"),
("ㄑㄧㄚ","qia","cia"),
("ㄑㄧㄝ","qie","cie"),
("ㄑㄧㄠ","qiao","ciao"),
("ㄑㄧㄡ","qiu","ciou"),
("ㄑㄧㄢ","qian","cian"),
("ㄑㄧㄣ","qin","cin"),
("ㄑㄧㄤ","qiang","ciang"),
("ㄑㄧㄥ","qing","cing"),
("ㄑㄩ","qu","cyu"),
("ㄑㄩㄝ","que","cyue"),
("ㄑㄩㄢ","quan","cyuan"),
("ㄑㄩㄣ","qun","cyun"),
("ㄑㄩㄥ","qiong","cyong"),
("ㄒㄧ","xi","si"),
("ㄒㄧㄚ","xia","sia"),
("ㄒㄧㄝ","xie","sie"),
("ㄒㄧㄠ","xiao","siao"),
("ㄒㄧㄡ","xiu","siou"),
("ㄒㄧㄢ","xian","sian"),
("ㄒㄧㄣ","xin","sin"),
("ㄒㄧㄤ","xiang","siang"),
("ㄒㄧㄥ","xing","sing"),
("ㄒㄩ","xu","syu"),
("ㄒㄩㄝ","xue","syue"),
("ㄒㄩㄢ","xuan","syuan"),
("ㄒㄩㄣ","xun","syun"),
("ㄒㄩㄥ","xiong","syong"),
("ㄓ","zhi","jhih"),
("ㄓㄚ","zha","jha"),
("ㄓㄜ","zhe","jhe"),
("ㄓㄞ","zhai","jhai"),
("ㄓㄠ","zhao","jhao"),
("ㄓㄡ","zhou","jhou"),
("ㄓㄢ","zhan","jhan"),
("ㄓㄣ","zhen","jhen"),
("ㄓㄤ","zhang","jhang"),
("ㄓㄥ","zheng","jheng"),
("ㄓㄨ","zhu","jhu"),
("ㄓㄨㄚ","zhua","jhua"),
("ㄓㄨㄛ","zhuo","jhuo"),
("ㄓㄨㄞ","zhuai","jhuai"),
("ㄓㄨㄟ","zhui","jhuei"),
("ㄓㄨㄢ","zhuan","jhuan"),
("ㄓㄨㄣ","zhun","jhun"),
("ㄓㄨㄤ","zhuang","jhuang"),
("ㄓㄨㄥ","zhong","jhong"),
("ㄔ","chi","chih"),
("ㄔㄚ","cha","cha"),
("ㄔㄜ","che","che"),
("ㄔㄞ","chai","chai"),
("ㄔㄠ","chao","chao"),
("ㄔㄡ","chou","chou"),
("ㄔㄢ","chan","chan"),
("ㄔㄣ","chen","chen"),
("ㄔㄤ","chang","chang"),
("ㄔㄥ","cheng","cheng"),
("ㄔㄨ","chu","chu"),
("ㄔㄨㄛ","chuo","chuo"),
("ㄔㄨㄞ","chuai","chuai"),
("ㄔㄨㄟ","chui","chuei"),
("ㄔㄨㄢ","chuan","chuan"),
("ㄔㄨㄣ","chun","chun"),
("ㄔㄨㄤ","chuang","chuang"),
("ㄔㄨㄥ","chong","chong"),
("ㄕ","shi","shih"),
("ㄕㄚ","sha","sha"),
("ㄕㄜ","she","she"),
("ㄕㄞ","shai","shai"),
("ㄕㄟ","shei","shei"),
("ㄕㄠ","shao","shao"),
("ㄕㄡ","shou","shou"),
("ㄕㄢ","shan","shan"),
("ㄕㄣ","shen","shen"),
("ㄕㄤ","shang","shang"),
("ㄕㄥ","sheng","sheng"),
("ㄕㄨ","shu","shu"),
("ㄕㄨㄚ","shua","shua"),
("ㄕㄨㄛ","shuo","shuo"),
("ㄕㄨㄞ","shuai","shuai"),
("ㄕㄨㄟ","shui","shuei"),
("ㄕㄨㄢ","shuan","shuan"),
("ㄕㄨㄣ","shun","shun"),
("ㄕㄨㄤ","shuang","shuang"),
("ㄖ","ri","rih"),
("ㄖㄜ","re","re"),
("ㄖㄠ","rao","rao"),
("ㄖㄡ","rou","rou"),
("ㄖㄢ","ran","ran"),
("ㄖㄣ","ren","ren"),
("ㄖㄤ","rang","rang"),
("ㄖㄨ","ru","ru"),
("ㄖㄨㄛ","ruo","ruo"),
("ㄖㄨㄟ","rui","ruei"),
("ㄖㄨㄢ","ruan","ruan"),
("ㄖㄨㄣ","run","run"),
("ㄖㄨㄥ","rong","rong"),
("ㄗ","zi","zih"),
("ㄗㄚ","za","za"),
("ㄗㄜ","ze","ze"),
("ㄗㄞ","zai","zai"),
("ㄗㄟ","zei","zei"),
("ㄗㄠ","zao","zao"),
("ㄗㄡ","zou","zou"),
("ㄗㄢ","zan","zan"),
("ㄗㄣ","zen","zen"),
("ㄗㄤ","zang","zang"),
("ㄗㄥ","zeng","zeng"),
("ㄗㄨ","zu","zu"),
("ㄗㄨㄛ","zuo","zuo"),
("ㄗㄨㄟ","zui","zuei"),
("ㄗㄨㄢ","zuan","zuan"),
("ㄗㄨㄣ","zun","zun"),
("ㄗㄨㄥ","zong","zong"),
("ㄘ","ci","cih"),
("ㄘㄚ","ca","ca"),
("ㄘㄜ","ce","ce"),
("ㄘㄞ","cai","cai"),
("ㄘㄠ","cao","cao"),
("ㄘㄡ","cou","cou"),
("ㄘㄢ","can","can"),
("ㄘㄣ","cen","cen"),
("ㄘㄤ","cang","cang"),
("ㄘㄥ","ceng","ceng"),
("ㄘㄨ","cu","cu"),
("ㄘㄨㄛ","cuo","cuo"),
("ㄘㄨㄟ","cui","cuei"),
("ㄘㄨㄢ","cuan","cuan"),
("ㄘㄨㄣ","cun","cun"),
("ㄘㄨㄥ","cong","cong"),
("ㄙ","si","sih"),
("ㄙㄚ","sa","sa"),
("ㄙㄜ","se","se"),
("ㄙㄞ","sai","sai"),
("ㄙㄠ","sao","sao"),
("ㄙㄡ","sou","sou"),
("ㄙㄢ","san","san"),
("ㄙㄣ","sen","sen"),
("ㄙㄤ","sang","sang"),
("ㄙㄥ","seng","seng"),
("ㄙㄨ","su","su"),
("ㄙㄨㄛ","suo","suo"),
("ㄙㄨㄟ","sui","suei"),
("ㄙㄨㄢ","suan","suan"),
("ㄙㄨㄣ","sun","sun"),
("ㄙㄨㄥ","song","song"),
("ㄚ","a","a"),
("ㄜ","e","e"),
("ㄞ","ai","ai"),
("ㄠ","ao","ao"),
("ㄡ","ou","ou"),
("ㄢ","an","an"),
("ㄣ","en","en"),
("ㄤ","ang","ang"),
("ㄦ","er","er"),
("ㄧ","yi","yi"),
("ㄧㄚ","ya","ya"),
("ㄧㄝ","ye","ye"),
("ㄧㄞ","yai","yai"),
("ㄧㄠ","yao","yao"),
("ㄧㄡ","you","you"),
("ㄧㄢ","yan","yan"),
("ㄧㄣ","yin","yin"),
("ㄧㄤ","yang","yang"),
("ㄧㄥ","ying","ying"),
("ㄨ","wu","wu"),
("ㄨㄚ","wa","wa"),
("ㄨㄛ","wo","wo"),
("ㄨㄞ","wai","wai"),
("ㄨㄟ","wei","wei"),
("ㄨㄢ","wan","wan"),
("ㄨㄣ","wen","wun"),
("ㄨㄤ","wang","wang"),
("ㄨㄥ","weng","wong"),
("ㄩ","yu","yu"),
("ㄩㄝ","yue","yue"),
("ㄩㄢ","yuan","yuan"),
("ㄩㄣ","yun","yun"),
("ㄩㄥ","yong","yong")]

hanpin2zhu = {x[1]: x[0] for x in zhuyin_hanpin_stdpin}
zhu2hanpin = {x[0]: x[1] for x in zhuyin_hanpin_stdpin}
